### ISSUE TITLE
VOICEVOXコアの依存をonnxruntime-rsから、本家のonnxruntime Rustバインディングに変更する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/onnxruntime#3]
VOICEVOX コア側に立っているこちらのPRと同一です。

- https://github.com/VOICEVOX/voicevox_core/issues/427

（とりあえずこのリポジトリの目標がわかるようにメモする意図でissue作成しました）

**Comment by qryxip** [comment]
<https://github.com/VOICEVOX/voicevox_core/issues/427#issuecomment-2123679331>

**Comment by Hiroshiba** [comment]
このリポジトリどうしましょうかね。
後で戻せるのか確認してからarchiveかなぁ。

あっでもまだ0.14系でアプデするかもだから、しばらく残しとこうかな。
そうします！
